- name: install and start nginx
  hosts: njdcsrv1 
  tasks:
         - name: Install nginx
           package:
             name: nginx
             state: present
           notify:
                nginxhandler
  handlers:
       - name: nginxhandler
         service:
           name: nginx
           state: started