---
- name: install and start nginx
  hosts: all
  
  tasks:
    - name: install latest nginx package 
	   yum:
  	     name: nginx
  	     state: latest

    - name: start httpd  
      service:
        name: nginx
        state: started