---
- name: Get ping response
  hosts: webservers
    #  become: true
    #  become_user: aleberkn

  tasks:
    - name: ping
      ping:
      register: result

    - name: print result
      debug:
        msg: "{{ result }}"
~                           